// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Placely.Infrastructure;

#nullable disable

namespace Placely.Main.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240420180043_downgrade_field_of_second_man_in_chat_fix_relations")]
    partial class downgrade_field_of_second_man_in_chat_fix_relations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Placely.Data.Entities.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("directory_path");

                    b.Property<long>("FirstUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("first_user_id");

                    b.Property<long?>("LandlordId")
                        .HasColumnType("bigint")
                        .HasColumnName("landlord_id");

                    b.Property<long>("SecondUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("second_user_id");

                    b.Property<long?>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.HasIndex("FirstUserId")
                        .HasDatabaseName("ix_chats_first_user_id");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_chats_landlord_id");

                    b.HasIndex("SecondUserId")
                        .HasDatabaseName("ix_chats_second_user_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_chats_tenant_id");

                    b.ToTable("chats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DirectoryPath = "/chat-t-1-l-1",
                            FirstUserId = 1L,
                            SecondUserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            DirectoryPath = "/chat-t-2-l-1",
                            FirstUserId = 2L,
                            SecondUserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            DirectoryPath = "/chat-t-2-l-2",
                            FirstUserId = 2L,
                            SecondUserId = 2L
                        });
                });

            modelBuilder.Entity("Placely.Data.Entities.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FinalizedPathDocx")
                        .HasColumnType("text")
                        .HasColumnName("finalized_path_docx");

                    b.Property<string>("FinalizedPathPdf")
                        .HasColumnType("text")
                        .HasColumnName("finalized_path_pdf");

                    b.Property<long>("LandlordId")
                        .HasColumnType("bigint")
                        .HasColumnName("landlord_id");

                    b.Property<DateTime>("LeaseEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_end_date");

                    b.Property<DateTime>("LeaseStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_start_date");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint")
                        .HasColumnName("property_id");

                    b.Property<string>("TemplateFieldsPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Data/contracts/default/default_fields.json")
                        .HasColumnName("template_fields_path");

                    b.Property<string>("TemplatePath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Data/contracts/default/default_template.docx")
                        .HasColumnName("template_path");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_contracts_landlord_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_contracts_property_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contracts_tenant_id");

                    b.ToTable("contracts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            LandlordId = 1L,
                            LeaseEndDate = new DateTime(2024, 5, 20, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6852),
                            LeaseStartDate = new DateTime(2024, 4, 13, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6849),
                            PropertyId = 1L,
                            TenantId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            LandlordId = 1L,
                            LeaseEndDate = new DateTime(2024, 5, 4, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6859),
                            LeaseStartDate = new DateTime(2024, 4, 20, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6859),
                            PropertyId = 2L,
                            TenantId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            LandlordId = 2L,
                            LeaseEndDate = new DateTime(2024, 4, 21, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6862),
                            LeaseStartDate = new DateTime(2024, 4, 18, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6861),
                            PropertyId = 3L,
                            TenantId = 3L
                        });
                });

            modelBuilder.Entity("Placely.Data.Entities.Landlord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_address");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_landlords");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_landlords_tenant_id");

                    b.ToTable("landlords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ContactAddress = "some address 1",
                            TenantId = 4L
                        },
                        new
                        {
                            Id = 2L,
                            ContactAddress = "some address 2",
                            TenantId = 5L
                        },
                        new
                        {
                            Id = 3L,
                            ContactAddress = "some address 3",
                            TenantId = 6L
                        });
                });

            modelBuilder.Entity("Placely.Data.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_messages_author_id");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_messages_chat_id");

                    b.ToTable("messages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = 1L,
                            ChatId = 1L,
                            Content = "message 1",
                            Date = new DateTime(2024, 4, 18, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6968)
                        },
                        new
                        {
                            Id = 2L,
                            AuthorId = 4L,
                            ChatId = 1L,
                            Content = "message 2",
                            Date = new DateTime(2024, 4, 19, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(7011)
                        },
                        new
                        {
                            Id = 3L,
                            AuthorId = 2L,
                            ChatId = 2L,
                            Content = "message with file",
                            Date = new DateTime(2024, 4, 14, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(7013),
                            FilePath = "smt"
                        });
                });

            modelBuilder.Entity("Placely.Data.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint")
                        .HasColumnName("receiver_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_notifications_receiver_id");

                    b.ToTable("notifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Content = "This is some helpful information",
                            Date = new DateOnly(2024, 4, 20),
                            IsDeleted = false,
                            ReceiverId = 2L,
                            Title = "Info"
                        },
                        new
                        {
                            Id = 2L,
                            Content = "This is some helpful information",
                            Date = new DateOnly(2024, 4, 20),
                            IsDeleted = false,
                            ReceiverId = 2L,
                            Title = "Info"
                        },
                        new
                        {
                            Id = 3L,
                            Content = "This is already readed some helpful information",
                            Date = new DateOnly(2024, 4, 20),
                            IsDeleted = false,
                            ReceiverId = 3L,
                            Title = "Info"
                        },
                        new
                        {
                            Id = 4L,
                            Content = "This is already readed some helpful information",
                            Date = new DateOnly(2024, 4, 20),
                            IsDeleted = true,
                            ReceiverId = 3L,
                            Title = "Info"
                        },
                        new
                        {
                            Id = 5L,
                            Content = "This is request on reservation",
                            Date = new DateOnly(2024, 4, 20),
                            IsDeleted = false,
                            ReceiverId = 4L,
                            Title = "Request"
                        },
                        new
                        {
                            Id = 6L,
                            Content = "This is readed request on reservation",
                            Date = new DateOnly(2024, 4, 20),
                            IsDeleted = true,
                            ReceiverId = 5L,
                            Title = "Request"
                        });
                });

            modelBuilder.Entity("Placely.Data.Entities.PreviousPassword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_previous_passwords");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_previous_passwords_tenant_id");

                    b.ToTable("previous_passwords", (string)null);
                });

            modelBuilder.Entity("Placely.Data.Entities.PriceList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("PeriodLong")
                        .HasColumnType("integer")
                        .HasColumnName("period_long");

                    b.Property<int>("PeriodMedium")
                        .HasColumnType("integer")
                        .HasColumnName("period_medium");

                    b.Property<int>("PeriodShort")
                        .HasColumnType("integer")
                        .HasColumnName("period_short");

                    b.HasKey("Id")
                        .HasName("pk_prices");

                    b.ToTable("prices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            PeriodLong = 11,
                            PeriodMedium = 111,
                            PeriodShort = 1111
                        },
                        new
                        {
                            Id = 2L,
                            PeriodLong = 22,
                            PeriodMedium = 222,
                            PeriodShort = 2222
                        },
                        new
                        {
                            Id = 3L,
                            PeriodLong = 33,
                            PeriodMedium = 333,
                            PeriodShort = 3333
                        });
                });

            modelBuilder.Entity("Placely.Data.Entities.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<long>("PriceListId")
                        .HasColumnType("bigint")
                        .HasColumnName("price_list_id");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publication_date");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_properties_owner_id");

                    b.HasIndex("PriceListId")
                        .IsUnique()
                        .HasDatabaseName("ix_properties_price_list_id");

                    b.ToTable("properties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Flat property address",
                            Description = "Flat property description",
                            OwnerId = 1L,
                            PriceListId = 1L,
                            PublicationDate = new DateTime(2024, 4, 19, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6739),
                            Rating = 0.0,
                            Type = 2
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Hostel property address",
                            Description = "Hostel property description",
                            OwnerId = 1L,
                            PriceListId = 2L,
                            PublicationDate = new DateTime(2024, 3, 21, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6783),
                            Rating = 0.0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Villa property address",
                            Description = "Villa property description",
                            OwnerId = 2L,
                            PriceListId = 3L,
                            PublicationDate = new DateTime(2024, 2, 20, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6786),
                            Rating = 0.0,
                            Type = 3
                        });
                });

            modelBuilder.Entity("Placely.Data.Entities.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date_time");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("text")
                        .HasColumnName("decline_reason");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_date");

                    b.Property<byte>("GuestsAmount")
                        .HasColumnType("smallint")
                        .HasColumnName("guests_amount");

                    b.Property<long>("LandlordId")
                        .HasColumnType("bigint")
                        .HasColumnName("landlord_id");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint")
                        .HasColumnName("property_id");

                    b.Property<int>("ReservationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_status");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("LandlordId")
                        .HasDatabaseName("ix_reservations_landlord_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_reservations_property_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_reservations_tenant_id");

                    b.ToTable("reservations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDateTime = new DateTime(2024, 3, 31, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6890),
                            Duration = new TimeSpan(37, 0, 0, 0, 0),
                            EntryDate = new DateTime(2024, 4, 13, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6892),
                            GuestsAmount = (byte)3,
                            LandlordId = 1L,
                            PropertyId = 1L,
                            ReservationStatus = 1,
                            TenantId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreationDateTime = new DateTime(2024, 4, 17, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6894),
                            Duration = new TimeSpan(14, 0, 0, 0, 0),
                            EntryDate = new DateTime(2024, 4, 20, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6895),
                            GuestsAmount = (byte)1,
                            LandlordId = 1L,
                            PropertyId = 2L,
                            ReservationStatus = 1,
                            TenantId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CreationDateTime = new DateTime(2024, 4, 17, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6896),
                            Duration = new TimeSpan(3, 0, 0, 0, 0),
                            EntryDate = new DateTime(2024, 4, 18, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6897),
                            GuestsAmount = (byte)2,
                            LandlordId = 2L,
                            PropertyId = 3L,
                            ReservationStatus = 1,
                            TenantId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            CreationDateTime = new DateTime(2024, 4, 20, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6899),
                            Duration = new TimeSpan(10, 0, 0, 0, 0),
                            EntryDate = new DateTime(2024, 4, 24, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6899),
                            GuestsAmount = (byte)3,
                            LandlordId = 1L,
                            PropertyId = 2L,
                            ReservationStatus = 0,
                            TenantId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CreationDateTime = new DateTime(2024, 4, 10, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6901),
                            DeclineReason = "too many guests",
                            Duration = new TimeSpan(10, 0, 0, 0, 0),
                            EntryDate = new DateTime(2024, 4, 24, 18, 0, 42, 906, DateTimeKind.Utc).AddTicks(6902),
                            GuestsAmount = (byte)34,
                            LandlordId = 2L,
                            PropertyId = 3L,
                            ReservationStatus = 2,
                            TenantId = 3L
                        });
                });

            modelBuilder.Entity("Placely.Data.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint")
                        .HasColumnName("property_id");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_reviews_author_id");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_reviews_property_id");

                    b.ToTable("reviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = 1L,
                            Content = "review 1",
                            PropertyId = 1L,
                            Rating = 1L
                        },
                        new
                        {
                            Id = 2L,
                            AuthorId = 2L,
                            Content = "review 2",
                            PropertyId = 2L,
                            Rating = 2L
                        },
                        new
                        {
                            Id = 3L,
                            AuthorId = 3L,
                            Content = "review 3",
                            PropertyId = 3L,
                            Rating = 3L
                        },
                        new
                        {
                            Id = 4L,
                            AuthorId = 4L,
                            Content = "review 4",
                            PropertyId = 1L,
                            Rating = 4L
                        },
                        new
                        {
                            Id = 5L,
                            AuthorId = 5L,
                            Content = "review 5",
                            PropertyId = 2L,
                            Rating = 5L
                        });
                });

            modelBuilder.Entity("Placely.Data.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text")
                        .HasColumnName("about");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text")
                        .HasColumnName("avatar_path");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("UserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("user_role");

                    b.Property<string>("Work")
                        .HasColumnType("text")
                        .HasColumnName("work");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            About = "I'm test tenant 1",
                            AvatarPath = "",
                            Email = "test.tenant.1@email.domen",
                            Name = "Test tenant 1",
                            Password = "test.tenant.1@email.domen",
                            PhoneNumber = "111 1111 11 11",
                            UserRole = 0,
                            Work = "I'm working nowhere"
                        },
                        new
                        {
                            Id = 2L,
                            About = "I'm test tenant 2",
                            AvatarPath = "",
                            Email = "test.tenant.2@email.domen",
                            Name = "Test tenant 2",
                            Password = "test.tenant.2@email.domen",
                            PhoneNumber = "222 2222 22 22",
                            UserRole = 0,
                            Work = "I'm working nowhere"
                        },
                        new
                        {
                            Id = 3L,
                            About = "I'm test tenant 3",
                            AvatarPath = "",
                            Email = "test.tenant.3@email.domen",
                            Name = "Test tenant 3",
                            Password = "test.tenant.3@email.domen",
                            PhoneNumber = "333 3333 33 33",
                            UserRole = 0,
                            Work = "I'm working nowhere"
                        },
                        new
                        {
                            Id = 4L,
                            About = "I'm test landlord 1",
                            AvatarPath = "",
                            Email = "test.landlord.1@email.domen",
                            Name = "Test landlord 1",
                            Password = "test.landlord.1@email.domen",
                            PhoneNumber = "111 1111 11 11",
                            UserRole = 0,
                            Work = "I'm working here"
                        },
                        new
                        {
                            Id = 5L,
                            About = "I'm test landlord 2",
                            AvatarPath = "",
                            Email = "test.landlord.2@email.domen",
                            Name = "Test landlord 2",
                            Password = "test.landlord.2@email.domen",
                            PhoneNumber = "222 2222 22 22",
                            UserRole = 0,
                            Work = "I'm working here"
                        },
                        new
                        {
                            Id = 6L,
                            About = "I'm test landlord 3",
                            AvatarPath = "",
                            Email = "test.landlord.3@email.domen",
                            Name = "Test landlord 3",
                            Password = "test.landlord.3@email.domen",
                            PhoneNumber = "333 3333 33 33",
                            UserRole = 0,
                            Work = "I'm working here"
                        });
                });

            modelBuilder.Entity("PropertyTenant", b =>
                {
                    b.Property<long>("FavouriteId")
                        .HasColumnType("bigint")
                        .HasColumnName("favourite_id");

                    b.Property<long>("InFavouritesId")
                        .HasColumnType("bigint")
                        .HasColumnName("in_favourites_id");

                    b.HasKey("FavouriteId", "InFavouritesId")
                        .HasName("pk_property_tenant");

                    b.HasIndex("InFavouritesId")
                        .HasDatabaseName("ix_property_tenant_in_favourites_id");

                    b.ToTable("property_tenant", (string)null);
                });

            modelBuilder.Entity("Placely.Data.Entities.Chat", b =>
                {
                    b.HasOne("Placely.Data.Entities.Tenant", "FirstUser")
                        .WithMany()
                        .HasForeignKey("FirstUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chats_tenants_first_user_id");

                    b.HasOne("Placely.Data.Entities.Landlord", null)
                        .WithMany("Chats")
                        .HasForeignKey("LandlordId")
                        .HasConstraintName("fk_chats_landlords_landlord_id");

                    b.HasOne("Placely.Data.Entities.Tenant", "SecondUser")
                        .WithMany()
                        .HasForeignKey("SecondUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chats_tenants_second_user_id");

                    b.HasOne("Placely.Data.Entities.Tenant", null)
                        .WithMany("Chats")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_chats_tenants_tenant_id");

                    b.Navigation("FirstUser");

                    b.Navigation("SecondUser");
                });

            modelBuilder.Entity("Placely.Data.Entities.Contract", b =>
                {
                    b.HasOne("Placely.Data.Entities.Landlord", "Landlord")
                        .WithMany("Contracts")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_landlords_landlord_id");

                    b.HasOne("Placely.Data.Entities.Property", "Property")
                        .WithMany("Contracts")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_properties_property_id");

                    b.HasOne("Placely.Data.Entities.Tenant", "Tenant")
                        .WithMany("Contracts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_tenants_tenant_id");

                    b.Navigation("Landlord");

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Placely.Data.Entities.Landlord", b =>
                {
                    b.HasOne("Placely.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_landlords_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Placely.Data.Entities.Message", b =>
                {
                    b.HasOne("Placely.Data.Entities.Tenant", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_tenants_author_id");

                    b.HasOne("Placely.Data.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_chats_chat_id");

                    b.Navigation("Author");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Placely.Data.Entities.Notification", b =>
                {
                    b.HasOne("Placely.Data.Entities.Tenant", "Receiver")
                        .WithMany("Notifications")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_tenants_receiver_id");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Placely.Data.Entities.PreviousPassword", b =>
                {
                    b.HasOne("Placely.Data.Entities.Tenant", "Tenant")
                        .WithMany("PreviousPasswords")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_previous_passwords_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Placely.Data.Entities.Property", b =>
                {
                    b.HasOne("Placely.Data.Entities.Landlord", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_properties_landlords_owner_id");

                    b.HasOne("Placely.Data.Entities.PriceList", "PriceList")
                        .WithMany()
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_properties_prices_price_list_id");

                    b.Navigation("Owner");

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("Placely.Data.Entities.Reservation", b =>
                {
                    b.HasOne("Placely.Data.Entities.Landlord", "Landlord")
                        .WithMany("Reservations")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_landlords_landlord_id");

                    b.HasOne("Placely.Data.Entities.Property", "Property")
                        .WithMany("Reservations")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_properties_property_id");

                    b.HasOne("Placely.Data.Entities.Tenant", "Tenant")
                        .WithMany("Reservations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_tenants_tenant_id");

                    b.Navigation("Landlord");

                    b.Navigation("Property");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Placely.Data.Entities.Review", b =>
                {
                    b.HasOne("Placely.Data.Entities.Tenant", "Author")
                        .WithMany("Reviews")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_tenants_author_id");

                    b.HasOne("Placely.Data.Entities.Property", "Property")
                        .WithMany("Reviews")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_properties_property_id");

                    b.Navigation("Author");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyTenant", b =>
                {
                    b.HasOne("Placely.Data.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("FavouriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_tenant_properties_favourite_id");

                    b.HasOne("Placely.Data.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("InFavouritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_property_tenant_tenants_in_favourites_id");
                });

            modelBuilder.Entity("Placely.Data.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Placely.Data.Entities.Landlord", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Contracts");

                    b.Navigation("Properties");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Placely.Data.Entities.Property", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Placely.Data.Entities.Tenant", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Contracts");

                    b.Navigation("Notifications");

                    b.Navigation("PreviousPasswords");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
